const peoples = [
  {
    name: "Alice Johnson",
    age: 28,
    email: "alice.johnson@example.com",
    gender: "Female",
    maritalStatus: "Single",
    picture: "https://randomuser.me/api/portraits/women/1.jpg",
    address: "123 Main St, Springfield, IL",
  },
  {
    name: "Bob Smith",
    age: 34,
    email: "bob.smith@example.com",
    gender: "Male",
    maritalStatus: "Married",
    picture: "https://randomuser.me/api/portraits/men/2.jpg",
    address: "456 Oak Ave, Lincoln, NE",
  },
  {
    name: "Cathy Lee",
    age: 25,
    email: "cathy.lee@example.com",
    gender: "Female",
    maritalStatus: "Single",
    picture: "https://randomuser.me/api/portraits/women/3.jpg",
    address: "789 Pine Rd, Madison, WI",
  },
  {
    name: "David Kim",
    age: 40,
    email: "david.kim@example.com",
    gender: "Male",
    maritalStatus: "Married",
    picture: "https://randomuser.me/api/portraits/men/4.jpg",
    address: "321 Maple St, Austin, TX",
  },
  {
    name: "Emma Brown",
    age: 31,
    email: "emma.brown@example.com",
    gender: "Female",
    maritalStatus: "Divorced",
    picture: "https://randomuser.me/api/portraits/women/5.jpg",
    address: "654 Cedar Ave, Portland, OR",
  },
  {
    name: "Frank Miller",
    age: 29,
    email: "frank.miller@example.com",
    gender: "Male",
    maritalStatus: "Single",
    picture: "https://randomuser.me/api/portraits/men/6.jpg",
    address: "987 Birch Blvd, Denver, CO",
  },
  {
    name: "Grace Chen",
    age: 36,
    email: "grace.chen@example.com",
    gender: "Female",
    maritalStatus: "Married",
    picture: "https://randomuser.me/api/portraits/women/7.jpg",
    address: "159 Spruce Ln, Seattle, WA",
  },
  {
    name: "Henry Wilson",
    age: 42,
    email: "henry.wilson@example.com",
    gender: "Male",
    maritalStatus: "Widowed",
    picture: "https://randomuser.me/api/portraits/men/8.jpg",
    address: "753 Willow Dr, Miami, FL",
  },
  {
    name: "Ivy Patel",
    age: 27,
    email: "ivy.patel@example.com",
    gender: "Female",
    maritalStatus: "Single",
    picture: "https://randomuser.me/api/portraits/women/9.jpg",
    address: "852 Aspen Ct, Boston, MA",
  },
  {
    name: "Jack Lee",
    age: 33,
    email: "jack.lee@example.com",
    gender: "Male",
    maritalStatus: "Married",
    picture: "https://randomuser.me/api/portraits/men/10.jpg",
    address: "951 Elm St, San Diego, CA",
  },
];

export default peoples;
